[2024-08-17T15:32:57.774+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-17T15:32:57.795+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.1 manual__2024-08-17T15:32:57.084129+00:00 [queued]>
[2024-08-17T15:32:57.807+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.1 manual__2024-08-17T15:32:57.084129+00:00 [queued]>
[2024-08-17T15:32:57.808+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-17T15:32:57.825+0000] {taskinstance.py:2879} INFO - Executing <Task(SparkSubmitOperator): 1> on 2024-08-17 15:32:57.084129+00:00
[2024-08-17T15:32:57.833+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=943) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-17T15:32:57.833+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag', '1', 'manual__2024-08-17T15:32:57.084129+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpba3ptmfe']
[2024-08-17T15:32:57.835+0000] {standard_task_runner.py:72} INFO - Started process 944 to run task
[2024-08-17T15:32:57.835+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask 1
[2024-08-17T15:32:57.893+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag.1 manual__2024-08-17T15:32:57.084129+00:00 [running]> on host e46ae3fe7248
[2024-08-17T15:32:57.991+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='1' AIRFLOW_CTX_EXECUTION_DATE='2024-08-17T15:32:57.084129+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-17T15:32:57.084129+00:00'
[2024-08-17T15:32:57.992+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-17T15:32:58.020+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2024-08-17T15:32:58.021+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://master:7077 --conf spark.executor.memory=2g --conf spark.driver.memory=2g --conf spark.executor.cores=1 --conf spark.cores.max=1 --conf spark.executor.instances=1 --name connect_task --deploy-mode client D:\personal\century_health_assignment\include\app.py
[2024-08-17T15:32:58.075+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-08-17T15:32:58.077+0000] {spark_submit.py:579} INFO - JAVA_HOME is not set
[2024-08-17T15:32:58.089+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://master:7077 --conf spark.executor.memory=2g --conf spark.driver.memory=2g --conf spark.executor.cores=1 --conf spark.cores.max=1 --conf spark.executor.instances=1 --name connect_task --deploy-mode client D:\personal\century_health_assignment\include\app.py. Error code is: 1.
[2024-08-17T15:32:58.094+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=my_dag, task_id=1, run_id=manual__2024-08-17T15:32:57.084129+00:00, execution_date=20240817T153257, start_date=20240817T153257, end_date=20240817T153258
[2024-08-17T15:32:58.108+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-17T15:32:58.109+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task 1 (Cannot execute: spark-submit --master spark://master:7077 --conf spark.executor.memory=2g --conf spark.driver.memory=2g --conf spark.executor.cores=1 --conf spark.cores.max=1 --conf spark.executor.instances=1 --name connect_task --deploy-mode client D:\personal\century_health_assignment\include\app.py. Error code is: 1.; 944)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://master:7077 --conf spark.executor.memory=2g --conf spark.driver.memory=2g --conf spark.executor.cores=1 --conf spark.cores.max=1 --conf spark.executor.instances=1 --name connect_task --deploy-mode client D:\personal\century_health_assignment\include\app.py. Error code is: 1.
[2024-08-17T15:32:58.133+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-17T15:32:58.152+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-17T15:32:58.156+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
